# Generated by Django 5.0.6 on 2024-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiny',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterField(
            model_name='tiny',
            name='full_url',
            field=models.CharField(max_length=255, unique=True, verbose_name='Полный Адрес'),
        ),
        migrations.AlterField(
            model_name='tiny',
            name='short_url',
            field=models.CharField(max_length=50, unique=True, verbose_name='Короткий Адрес'),
        ),
    ]
